

# This file was *autogenerated* from the file scripts/characters.sage
from sage.all_cmdline import *   # import sage library

_sage_const_36 = Integer(36); _sage_const_1 = Integer(1); _sage_const_6 = Integer(6); _sage_const_10 = Integer(10); _sage_const_4 = Integer(4); _sage_const_54 = Integer(54); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_495 = Integer(495); _sage_const_0 = Integer(0)# Exact character data for H = Aut(Delta) (order 54) acting on V* (9 coordinates), Sym^4 V*, I_4, A_4.
# Independent of Macaulay2. Reads the facet list and the 54 permutations.
import itertools, json
facets=[]
for line in open("data/facets_chapoton_manivel_1109.6490v1.txt"):
    line=line.strip()
    if not line or line.startswith("#"): continue
    for tok in line.split(): facets.append(frozenset(int(c) for c in tok))
assert len(facets)==_sage_const_36 
faces=set()
for F in facets:
    for k in range(_sage_const_1 ,_sage_const_6 ):
        for s in itertools.combinations(sorted(F),k): faces.add(frozenset(s))
nonfaces4=sorted([frozenset(s) for s in itertools.combinations(range(_sage_const_1 ,_sage_const_10 ),_sage_const_4 ) if frozenset(s) not in faces], key=lambda s: sorted(s))
assert len(nonfaces4)==_sage_const_36 
perms=[]
for line in open("data/group_Aut54.txt"):
    line=line.strip()
    if not line or line.startswith("#"): continue
    perms.append(tuple(int(c) for c in line.split()))
assert len(perms)==_sage_const_54 
# check each perm preserves facets
for g in perms:
    img=set(frozenset(g[i-_sage_const_1 ] for i in F) for F in facets)
    assert img==set(facets)
G=PermutationGroup([Permutation(list(g)) for g in perms])
assert G.order()==_sage_const_54 
print("group_order",G.order(),"structure",G.structure_description())
CC=G.conjugacy_classes()
print("number_of_conjugacy_classes",len(CC))
# degree-4 monomials as exponent vectors
monos=[e for e in itertools.product(range(_sage_const_5 ),repeat=_sage_const_9 ) if sum(e)==_sage_const_4 ]
assert len(monos)==_sage_const_495 
def mono_support(e): return frozenset(i+_sage_const_1  for i,x in enumerate(e) if x>_sage_const_0 )
def in_I(e):
    # monomial in I_Delta iff its support is a nonface
    return mono_support(e) not in faces
I4=[e for e in monos if in_I(e)]; assert len(I4)==_sage_const_36 
def act(g,e):
    # x_i -> x_{g(i)}: exponent at g(i) becomes e_i
    out=[_sage_const_0 ]*_sage_const_9 
    for i in range(_sage_const_9 ): out[g[i]-_sage_const_1 ]=e[i]
    return tuple(out)
def fixed_count(g,L):
    return sum(_sage_const_1  for e in L if act(g,e)==e)
def cycle_type(g):
    seen=set(); ct=[]
    for i in range(_sage_const_1 ,_sage_const_10 ):
        if i in seen: continue
        c=_sage_const_0 ; j=i
        while j not in seen: seen.add(j); j=g[j-_sage_const_1 ]; c+=_sage_const_1 
        ct.append(c)
    return tuple(sorted(ct,reverse=True))
rows=[]
for cl in CC:
    rep=cl.representative(); g=tuple(rep(i) for i in range(_sage_const_1 ,_sage_const_10 ))
    chiV=sum(_sage_const_1  for i in range(_sage_const_9 ) if g[i]==i+_sage_const_1 )
    chiS4=fixed_count(g,monos); chiI=fixed_count(g,I4); chiA=chiS4-chiI
    rows.append(dict(size=len(cl),order=rep.order(),cycle_type=cycle_type(g),rep=g,chiV=chiV,chiSym4=chiS4,chiI4=chiI,chiA4=chiA))
for r in rows: print(r)
inv=lambda key: sum(r["size"]*r[key] for r in rows)/_sage_const_54 
print("invariant_dims: V*",inv("chiV"),"Sym4",inv("chiSym4"),"I4",inv("chiI4"),"A4",inv("chiA4"))
homIA=sum(r["size"]*r["chiI4"]*r["chiA4"] for r in rows)/_sage_const_54 
print("dim_Hom_H(I4,A4)",homIA)
# character table and decompositions
T=G.character_table()
irr=G.irreducible_characters()
print("irreducible_degrees",[chi.degree() for chi in irr])
def decompose(vals):
    # vals: list of character values per conjugacy class in CC order
    chi=ClassFunction(G,[QQbar(v) for v in vals]) if False else None
    res=[]
    for k,psi in enumerate(irr):
        s=sum(rows[c]["size"]*vals[c]*conjugate(psi.values()[c]) for c in range(len(CC)))/_sage_const_54 
        res.append(s)
    return res
for key in ["chiV","chiSym4","chiI4","chiA4"]:
    vals=[r[key] for r in rows]
    dec=decompose(vals)
    print("decomposition",key,[str(d) for d in dec])
# also the permutation action of H on the 36 generators: orbit sizes and stabilizers
orbits=[]
seen=set()
for e in I4:
    if e in seen: continue
    O=set(act(g,e) for g in perms); seen|=O; orbits.append(sorted(O))
print("generator_orbit_sizes",[len(O) for O in orbits])
conv=lambda v: [int(x) for x in v] if isinstance(v,tuple) else int(v)
json.dump({"classes":[{k:conv(v) for k,v in r.items()} for r in rows],
           "irreducible_degrees":[int(chi.degree()) for chi in irr],
           "decompositions":{key:[str(d) for d in decompose([r[key] for r in rows])] for key in ["chiV","chiSym4","chiI4","chiA4"]},
           "generator_orbit_sizes":[len(O) for O in orbits],
           "dim_Hom_H_I4_A4":str(homIA)},open("certificates/characters.json","w"),indent=_sage_const_1 )
print("CHARACTERS_DONE")

