-- Fixed loci of the translation subgroup on the invariant family: for g = (123)(456)(789) (a translation of
-- F_3^2 acting on the 9 vertices), Fix(g) in P^8 is the disjoint union of three planes E_zeta = {x_{i+3} = zeta x_i}
-- (eigenvalues zeta = 1, w, w^2).  On a smooth fibre X_t with the (exactly invariant) H-action, X_t^g = X_t cap Fix(g)
-- must be smooth, so every zero-dimensional component of X_t cap E_zeta must be a reduced point.  On X_0 the
-- intersection with each plane is three points of multiplicity three (local model b^3 = 0).  We compute the
-- scheme X_q cap E_1 (over QQ) and X_q cap E_w (over QQ[w]/(w^2+w+1)) modulo q^(N+1), on the line (t_1,t_2)=(q,c q),
-- and report the q-adic behaviour of its length-3 fat points (do they split to first order?).
-- Usage: M2 --script scripts/fixed_locus_test.m2 <statefile> <N> <c>
args = commandLine; statefile = args#(#args-3); N = value args#(#args-2); cval = value args#(#args-1);
SB = QQ[t_1, t_2, x_1..x_9, Degrees => {{0,1},{0,1},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0},{1,0}}];
load statefile;
Ftot = sum apply(N+1, k -> value("F_"|toString k));
-- eigenvalue 1: x_1=x_2=x_3=u_1, x_4=x_5=x_6=u_2, x_7=x_8=x_9=u_3
P1 = QQ[q, u_1, u_2, u_3];
phi1 = map(P1, SB, {q, cval*q, u_1,u_1,u_1, u_2,u_2,u_2, u_3,u_3,u_3});
J1 = ideal phi1 Ftot + ideal(q^(N+1));
stdio << "E_1: ideal generated by " << numgens J1 << " forms" << endl;
-- the three fat points of X_0 cap E_1 are [1:0:0],[0:1:0],[0:0:1] in (u_1:u_2:u_3); look near [1:0:0]: u_1 = 1
A1 = QQ[q, a, b];  -- a = u_2, b = u_3
loc = map(A1, P1, {q, 1, a, b});
J1loc = loc J1;
stdio << "E_1 near [1:0:0]: generators mod q: " << toString flatten entries mingens sub(J1loc, {q => 0}) << endl;
-- eliminate to a monic-ish equation in b: compute Groebner basis in lex a > b > q? use elimination of a
G = gens gb J1loc;
stdio << "E_1 near [1:0:0], Groebner basis (first 12 elements): " << toString take(flatten entries G, 12) << endl;
-- Is the scheme X_q cap E_1 (mod q^(N+1)) reduced generically over q? Check: does q^N * (b^3 or a) vanish etc.
-- eigenvalue w: x_{i+3} = w x_i for i in 1..3 relative to E_w = {(x_1,x_2,x_3, w x_1, w x_2, w x_3, w^2 x_1, w^2 x_2, w^2 x_3)}?  For g: x_i -> x_{g(i)}, g=(123)(456)(789),
-- eigenvectors of the permutation matrix on the three 3-cycles: v = (u, w^k u, w^{2k} u) within each cycle; we take the cycle (1 2 3) etc.
Kw = toField(QQ[w]/(w^2+w+1));
Pw = Kw[q, u_1, u_2, u_3];
phiw = map(Pw, SB, {q, cval*q, u_1, w*u_1, w^2*u_1, u_2, w*u_2, w^2*u_2, u_3, w*u_3, w^2*u_3});
Jw = ideal phiw Ftot + ideal(q^(N+1));
Aw = Kw[q, a, b]; locw = map(Aw, Pw, {q, 1, a, b});
Jwloc = locw Jw;
stdio << "E_w near [1:0:0]: generators mod q: " << toString flatten entries mingens sub(Jwloc, {q => 0}) << endl;
Gw = gens gb Jwloc;
stdio << "E_w near [1:0:0], Groebner basis (first 12 elements): " << toString take(flatten entries Gw, 12) << endl;
stdio << "CHECK|E_1_local_ideal_mod_q^(N+1)|" << toString flatten entries G << endl;
stdio << "CHECK|E_w_local_ideal_mod_q^(N+1)|" << toString flatten entries Gw << endl;
stdio << "FIXED_LOCUS_DONE" << endl;
exit 0;
