#!/usr/bin/env python3
"""Independent exact verification (pure Python, fractions) of an invariant-lift state file produced by
scripts/invariant_lift.m2:  certificates/lift<N>_state_order<N>.m2.txt  defines F_0..F_N (1x36) and R_0..R_N (36x90)
over QQ[t_1,t_2,x_1..x_9].  Checks:
  (1) F_0 = the 36 Stanley-Reisner quartics and R_0 consists of 90 relations of F_0 (F_0 R_0 = 0), linearly independent;
  (2) (sum F_k)(sum R_k) == 0 modulo (t_1,t_2)^(N+1)  [flatness of the truncated family];
  (3) every F_k and R_k is exactly Aut(Delta)-invariant:  g(F_k) = F_k P_g  and  P_g g(R_k) = R_k C_g  with the
      constant matrices C_g determined by R_0 (so that the ideal generated by F(t) is H-stable and its generators are
      permuted by H);
  (4) all denominators are powers of 2 and 3 (the family is defined over Z[1/6] through this order);
  (5) F_1 = t_1 v_a + t_2 v_b with v_a, v_b as recorded, both killing the syzygies modulo I.
Usage: python3 scripts/verify_lift_state.py certificates/lift6_state_order6.m2.txt 6
"""
import sys, re, itertools, json
from fractions import Fraction
from collections import defaultdict

statefile, N = sys.argv[1], int(sys.argv[2])
VARS = ["t_1","t_2"] + ["x_%d"%i for i in range(1,10)]
VIDX = {v:i for i,v in enumerate(VARS)}
NV = len(VARS)

# ---------- sparse polynomial arithmetic: dict {exponent tuple: Fraction} ----------
def padd(p, q, s=1):
    r = dict(p)
    for m, c in q.items():
        v = r.get(m, 0) + s*c
        if v == 0: r.pop(m, None)
        else: r[m] = v
    return r
def pmul(p, q):
    r = defaultdict(Fraction)
    for m1, c1 in p.items():
        for m2, c2 in q.items():
            m = tuple(a+b for a,b in zip(m1,m2)); r[m] += c1*c2
    return {m:c for m,c in r.items() if c != 0}
def pscale(p, c): return {m: c*v for m,v in p.items()} if c != 0 else {}
def tdeg(m): return m[0]+m[1]
def ptrunc(p, N): return {m:c for m,c in p.items() if tdeg(m) <= N}

term_re = re.compile(r"\s*([+-]?)\s*(\(?\d+(?:/\d+)?\)?)?\*?((?:[tx]_\d(?:\^\d+)?\*?)*)")
def parse_poly(s):
    s = s.strip()
    if s == "0": return {}
    p = {}
    pos = 0
    # split into signed terms
    terms = re.findall(r"[+-]?[^+-]+", s.replace(" ", ""))
    for t in terms:
        sign = -1 if t.startswith("-") else 1
        t = t.lstrip("+-")
        coef = Fraction(1)
        m = re.match(r"^\((\d+)/(\d+)\)\*(.*)$", t)
        if m: coef = Fraction(int(m.group(1)), int(m.group(2))); t = m.group(3)
        else:
            m = re.match(r"^(\d+)\*(.*)$", t)
            if m: coef = Fraction(int(m.group(1))); t = m.group(2)
            elif re.match(r"^\d+$", t): coef = Fraction(int(t)); t = ""
        e = [0]*NV
        if t:
            for fac in t.split("*"):
                mm = re.match(r"^([tx]_\d)(?:\^(\d+))?$", fac)
                assert mm, (fac, s[:80])
                e[VIDX[mm.group(1)]] += int(mm.group(2) or 1)
        mono = tuple(e)
        p[mono] = p.get(mono, 0) + sign*coef
        if p[mono] == 0: del p[mono]
    return p
def parse_matrix(txt):
    body = txt[txt.index("{{")+2 : txt.rindex("}}")]
    rows = body.split("}, {")
    return [[parse_poly(e) for e in row.split(", ")] for row in rows]

src = open(statefile).read()
def grab(name):
    i = src.index("\n"+name+" = ") + 1
    j = src.index(";\n", i)
    return parse_matrix(src[i:j])
F = [grab("F_%d"%k) for k in range(N+1)]
R = [grab("R_%d"%k) for k in range(N+1)]
assert all(len(Fk)==1 and len(Fk[0])==36 for Fk in F)
assert all(len(Rk)==36 and all(len(r)==90 for r in Rk) for Rk in R)
print("parsed F_0..F_%d (1x36) and R_0..R_%d (36x90)" % (N,N))

# ---------- (1) F_0 and R_0 ----------
gens_txt = open("data/generators.m2.txt").read()
gens = re.findall(r"x_\d\*x_\d\*x_\d\*x_\d", gens_txt)
assert [parse_poly(g) for g in gens] == F[0][0], "F_0 is not the recorded generator list"
def matmul_rows(Frow, Rmat):  # (1x36)*(36x90)
    out = []
    for k in range(90):
        acc = {}
        for j in range(36):
            if Frow[j] and Rmat[j][k]: acc = padd(acc, pmul(Frow[j], Rmat[j][k]))
        out.append(acc)
    return out
assert all(p == {} for p in matmul_rows(F[0][0], R[0])), "F_0 R_0 != 0"
# linear independence of the 90 relations (each is a vector of 36 linear forms; flatten to coefficient vectors)
def flat_vec(col):
    v = {}
    for j in range(36):
        for m,c in R[0][j][col].items(): v[(j,m)] = c
    return v
keys = sorted({k for col in range(90) for k in flat_vec(col)})
M = [[flat_vec(col).get(k,0) for k in keys] for col in range(90)]
def rank(M):
    M = [row[:] for row in M]; r = 0; cols = len(M[0]) if M else 0
    for c in range(cols):
        piv = next((i for i in range(r, len(M)) if M[i][c] != 0), None)
        if piv is None: continue
        M[r], M[piv] = M[piv], M[r]
        for i in range(len(M)):
            if i != r and M[i][c] != 0:
                f = M[i][c]/M[r][c]; M[i] = [a - f*b for a,b in zip(M[i], M[r])]
        r += 1
    return r
assert rank(M) == 90, "R_0 columns not independent"
print("CHECK|F0_R0_zero_and_90_independent_relations|True")

# ---------- (2) flatness modulo (t)^(N+1) ----------
Ftot = [ {} for _ in range(36) ]
for k in range(N+1):
    for j in range(36): Ftot[j] = padd(Ftot[j], F[k][0][j])
Rtot = [[{} for _ in range(90)] for _ in range(36)]
for k in range(N+1):
    for j in range(36):
        for c in range(90):
            if R[k][j][c]: Rtot[j][c] = padd(Rtot[j][c], R[k][j][c])
prod = matmul_rows(Ftot, Rtot)
minorder = min((tdeg(m) for p in prod for m in p), default=None)
print("CHECK|FR_lowest_surviving_t_order|%s (must exceed %d)" % (minorder, N))
assert minorder is None or minorder > N
print("CHECK|FR_zero_mod_t^%d|True" % (N+1))

# ---------- (3) exact H-invariance ----------
perms = [tuple(int(c) for c in l.split()) for l in open("data/group_Aut54.txt") if l.strip() and not l.startswith("#")]
assert len(perms) == 54
def act_poly(g, p):  # x_i -> x_{g(i)}
    out = {}
    for m, c in p.items():
        e = list(m[:2]) + [0]*9
        for i in range(9): e[2 + g[i]-1] += m[2+i]
        out[tuple(e)] = c
    return out
gen_monos = F[0][0]
def gen_perm(g):  # pi(j) = index of g(m_j)
    return [gen_monos.index(act_poly(g, m)) for m in gen_monos]
def check_F(Fk, g, pi):
    # invariance g.F = F with (g.F)_k = g(F)_{pi^{-1}(k)}, i.e. g maps the j-th generator polynomial to the pi(j)-th one
    # (this is the convention that fixes F_0: g(m_j) = m_{pi(j)}).
    gF = [act_poly(g, f) for f in Fk]
    return all(gF[j] == Fk[pi[j]] for j in range(36))
# C_g from R_0:  R_0 C_g = P_g g(R_0)  where (P_g g(R_0))_{i,c} = g(R_0)_{pi^{-1}(i), c}
def solve_C(g, pi):
    pinv = [0]*36
    for j in range(36): pinv[pi[j]] = j
    # target columns: for each c, column vector of 36 linear forms  (P g(R0))_{i,c} = g(R0)_{pinv[i],c}
    # express as combination of the 90 columns of R_0: solve linear system on flattened vectors
    basis = [flat_vec(col) for col in range(90)]
    # build matrix once (90 columns) with the key set extended
    def flat_target(c):
        v = {}
        for i in range(36):
            for m, cc in act_poly(g, R[0][pinv[i]][c]).items(): v[(i,m)] = cc
        return v
    targets = [flat_target(c) for c in range(90)]
    allkeys = sorted({k for b in basis for k in b} | {k for t in targets for k in t})
    A = [[b.get(k,0) for b in basis] for k in allkeys]          # rows = keys, cols = 90
    B = [[t.get(k,0) for t in targets] for k in allkeys]        # rows = keys, cols = 90
    # gaussian elimination on augmented [A | B]
    nr, nc = len(A), 90
    Aug = [A[i] + B[i] for i in range(nr)]
    pivots = []; r = 0
    for c in range(nc):
        piv = next((i for i in range(r, nr) if Aug[i][c] != 0), None)
        if piv is None: continue
        Aug[r], Aug[piv] = Aug[piv], Aug[r]
        pv = Aug[r][c]; Aug[r] = [a/pv for a in Aug[r]]
        for i in range(nr):
            if i != r and Aug[i][c] != 0:
                f = Aug[i][c]; Aug[i] = [a - f*b for a,b in zip(Aug[i], Aug[r])]
        pivots.append(c); r += 1
    assert r == 90
    # consistency: rows beyond rank must be zero in B part
    for i in range(r, nr): assert all(v == 0 for v in Aug[i][nc:]), "P_g g(R_0) not in the span of R_0"
    C = [[Fraction(0)]*90 for _ in range(90)]
    for i, c in enumerate(pivots):
        for cc in range(90): C[c][cc] = Aug[i][nc+cc]
    return C, pinv
def check_R(Rk, g, pi, pinv, C):
    # want P_g g(R_k) = R_k C  entrywise: (P g(R_k))_{i,c} = g(R_k)_{pinv[i], c}
    for i in range(36):
        for c in range(90):
            lhs = act_poly(g, Rk[pinv[i]][c])
            rhs = {}
            for j in range(90):
                if C[j][c] != 0 and Rk[i][j]: rhs = padd(rhs, pscale(Rk[i][j], C[j][c]))
            if lhs != rhs: return False
    return True
okF = okR = True
for gi, g in enumerate(perms):
    pi = gen_perm(g)
    C, pinv = solve_C(g, pi)
    for k in range(N+1):
        okF &= check_F(F[k][0], g, pi)
        okR &= check_R(R[k], g, pi, pinv, C)
    if gi % 9 == 8: print("  invariance checked for %d group elements" % (gi+1))
print("CHECK|all_F_k_exactly_invariant|%s" % okF)
print("CHECK|all_R_k_exactly_invariant|%s" % okR)

# ---------- (4) denominators ----------
dens = set()
for Fk in F:
    for f in Fk[0]:
        for c in f.values(): dens.add(c.denominator)
for Rk in R:
    for row in Rk:
        for p in row:
            for c in p.values(): dens.add(c.denominator)
def only23(n):
    while n % 2 == 0: n //= 2
    while n % 3 == 0: n //= 3
    return n == 1
print("CHECK|denominators_only_2_and_3|%s  (max denominator %d)" % (all(only23(d) for d in dens), max(dens)))

# ---------- (5) F_1 kills the syzygies modulo I ----------
nonfaces = [frozenset(int(c) for c in re.findall(r"x_(\d)", g)) for g in gens]
def in_I(m):  # monomial exponent tuple -> support contains a nonface?
    supp = frozenset(i+1 for i in range(9) if m[2+i] > 0)
    return any(nf <= supp for nf in nonfaces)
def reduce_mod_I(p): return {m:c for m,c in p.items() if not in_I(m)}
prod1 = matmul_rows(F[1][0], R[0])
print("CHECK|F1_R0_zero_mod_I|%s" % all(reduce_mod_I(p) == {} for p in prod1))
supp = {j for j in range(36) if F[1][0][j]}
print("F_1 nonzero entries: %d; F_k nonzero entries for k=2..%d: %s" % (len(supp), N, [sum(1 for f in F[k][0] if f) for k in range(2,N+1)]))
print("R_k nonzero entries for k=1..%d: %s" % (N, [sum(1 for row in R[k] for p in row if p) for k in range(1,N+1)]))
print("VERIFY_LIFT_STATE_DONE")
